const person = [
  {
    id: 1,
    name: "Abdou Cissé",
    age: 38,
    img: "./assets/images/abdou.png",
    avatar: "./assets/avatar/abdou.jpg",
    stack: "Html",
    gender: "./assets/icons/whiteMale.png",
    description:
      "Abdou, jeune vieux de 38ans, soif de connaissances dans des domaines divers et variés. Eternel écrivain en herbe, j'écris souvent des éditos et analyses politiques à mes heures perdues. Passionné de la Tech, je me forge à explorer les métiers de la Tech dans une reconversion en cours.",
    quote: "L'effort fait les forts",
    levelHtml: 85,
    levelCss: 60,
    levelJs: 40,
    isPerfect: false,
  },
  {
    id: 2,
    name: "Cédric Righi",
    age: 20,
    img: "./assets/images/cedric.png",
    avatar: "./assets/avatar/cedric.jpg",
    stack: "Js",
    gender: "./assets/icons/male.png",
    description:
      "Passionné par l’informatique et la technologie, j’aime explorer des sujets techniques tout en gardant une touche d’humour dans ma vie quotidienne. Toujours à la recherche de nouveaux défis et d’apprentissages, j’aime varier les plaisirs entre logique et créativité.",
    quote: "Je vais vous prendre une glace blanche avec les SmicSmac.",
    levelHtml: 100,
    levelCss: 100,
    levelJs: 100,
    isPerfect: true,
  },
  {
    id: 3,
    name: "Charlotte Albouy",
    age: 33,
    img: "./assets/images/charlotte.png",
    avatar: "./assets/avatar/charlotte.jpg",
    stack: "Css",
    gender: "./assets/icons/whiteFemale.png",
    description:
      "Toujours de bonne humeur, je m'adapte facilement dans un nouvel environnement.",
    quote: "Better late than ugly.",
    levelHtml: 60,
    levelCss: 85,
    levelJs: 40,
    isPerfect: false,
  },
  {
    id: 4,
    name: "Emma Robinet",
    age: 28,
    img: "./assets/images/emma.png",
    avatar: "./assets/avatar/emma.jpg",
    stack: "Html",
    gender: "./assets/icons/female.png",
    description:
      "J'aime tout ce qui est à trait à l'Art (Photographie, Peinture, Digital etc.) et je ne peux pas me passer d'écouter de la musique.",
    quote:
      "Le bonheur, est-ce de se satisfaire du moment présent, quel qu'il soit ? Cela semble tout à la fois simple et difficile. - Vagabond",
    levelHtml: 100,
    levelCss: 100,
    levelJs: 100,
    isPerfect: true,
  },
  {
    id: 5,
    name: "Florentin Monteil",
    age: 39,
    img: "./assets/images/flo.png",
    avatar: "./assets/avatar/flo.jpg",
    stack: "Js",
    gender: "./assets/icons/male.png",
    description:
      "Acheteur de formation, développeur web en devenir, toujours curieux et désireux d'apprendre, adepte de bons mots et de calembours, de bonne humeur et constamment à l'écoute des autres. Sinon j'ai aussi des défauts.",
    quote:
      "Ris, tout le monde rira avec toi, pleure et tu seras seul à pleurer.",
    levelHtml: 100,
    levelCss: 100,
    levelJs: 100,
    isPerfect: true,
  },
  {
    id: 6,
    name: "Julien Joecker",
    age: 28,
    img: "./assets/images/julien.png",
    avatar: "./assets/avatar/julien.jpg",
    stack: "Js",
    gender: "./assets/icons/whiteMale.png",
    description:
      "Try harder, persévérant qui n'aime pas abandonner. Signe distinctif : oublie souvent de verrouiller son ordinateur.",
    quote:
      "Pour parler ? Au diable les misérables têtes d'œuf qui ont inventé le pourparler.",
    levelHtml: 40,
    levelCss: 60,
    levelJs: 85,
    isPerfect: false,
  },
  {
    id: 7,
    name: "Justine Cousin",
    age: 41,
    img: "./assets/images/justine.png",
    avatar: "./assets/avatar/justine.jpg",
    stack: "Css",
    gender: "./assets/icons/whiteFemale.png",
    description: "Maman touche à tout. Qui aime apprendre de nouvelles choses.",
    quote:
      "La vie, c'est comme une boîte de chocolats, on ne sait jamais sur quoi on va tomber.",
    levelHtml: 60,
    levelCss: 85,
    levelJs: 40,
    isPerfect: false,
  },
  {
    id: 8,
    name: "Mike Hatchi",
    age: 23,
    img: "./assets/images/mike.png",
    avatar: "./assets/avatar/mike.jpg",
    stack: "Js",
    gender: "./assets/icons/male.png",
    description:
      "Curieux et créatif, je trouve toujours des solutions avec une touche d’humour et de spontanéité. Ouvert et sociable, j'aime relever des défis tout en apportant une bonne dose de bonne humeur.",
    quote:
      "Toujours prêt à relever les défis… sauf ceux qui commencent avant 8h du matin.",
    levelHtml: 100,
    levelCss: 100,
    levelJs: 100,
    isPerfect: true,
  },
  {
    id: 9,
    name: "Radwan Osman",
    age: 24,
    img: "./assets/images/radwan.png",
    avatar: "./assets/avatar/radwan.jpg",
    stack: "Js",
    gender: "./assets/icons/whiteMale.png",
    description:
      "Je suis quelqu'un un peu tête en l'air du genre solitaire mais bonne ambiance , ma grande passion c'est le foot et j'adore vanner!",
    quote:
      "Ce ne sont pas les gens qui changent , ce sont les masques qui tombent",
    levelHtml: 60,
    levelCss: 40,
    levelJs: 85,
    isPerfect: false,
  },
  {
    id: 10,
    name: "Rémi Zickenheiner",
    age: 26,
    img: "./assets/images/remi.png",
    avatar: "./assets/avatar/remi.jpg",
    stack: "Js",
    gender: "./assets/icons/whiteMale.png",
    description: "Je suis quelqu'un et c'est deja bien !",
    quote: "Kebab",
    levelHtml: 60,
    levelCss: 40,
    levelJs: 85,
    isPerfect: false,
  },
  {
    id: 11,
    name: "Sylvia Barraud",
    age: 34,
    img: "./assets/images/sylvia.png",
    avatar: "./assets/avatar/sylvia.jpg",
    stack: "Js",
    gender: "./assets/icons/whiteFemale.png",
    description:
      "Curieuse et dynamique, j’adore apprendre et découvrir de nouvelles choses que ce soit professionnellement (notamment à travers la veille technologique) ou dans la sphère privée (la guitare, les langues, les voyages, la cuisine).  Aimant les responsabilités, je fais partie d’un groupe d’échange en anglais que j’ai plaisir à animer en tant qu’hôte.",
    quote:
      "There's always gonna be another mountain, I'm always gonna wanna make it move, Ain't about how fast I get there, Ain't about what's waiting on the other sid, It's the climb - Miley Cirus",
    levelHtml: 40,
    levelCss: 60,
    levelJs: 85,
    isPerfect: false,
  },
  {
    id: 12,
    name: "Thierry Lenepveu",
    age: 56,
    img: "./assets/images/thierry.png",
    avatar: "./assets/avatar/thierry.jpg",
    stack: "Js",
    gender: "./assets/icons/whiteMale.png",
    description:
      "Je suis quelqu'un de timide mais sérieux, avec une détermination inébranlable. J'avance avec persévérance vers les objectifs que je me suis fixé.",
    quote: "Je suis ton père.",
    levelHtml: 60,
    levelCss: 40,
    levelJs: 85,
    isPerfect: false,
  },
  {
    id: 13,
    name: "Tom Schricke",
    age: 25,
    img: "./assets/images/tom.png",
    avatar: "./assets/avatar/tom.jpg",
    stack: "Js",
    gender: "./assets/icons/whiteMale.png",
    description: "Salut, c'est Tom, j'aime l'apéro et la pétanque.",
    quote: "Pour vu que ça dure, la belle aventure.",
    levelHtml: 60,
    levelCss: 40,
    levelJs: 85,
    isPerfect: false,
  },
  {
    id: 14,
    name: "Arthur Heurtebise",
    age: 32,
    img: "./assets/images/Arthur.jpg",
    avatar: "./assets/avatar/arthur.jpg",
    stack: "Js",
    gender: "./assets/icons/male.png",
    description:
      "Papa, musicien et formateur, il y a peu de choses que j'aime plus que de transmettre mon savoir sur des sujets variés. Depuis 2022, c'est le développement web à la Wild Code School ! En février 2025, j'aurai la fierté d'avoir contribué à la reconversion professionnelle de 58 développeurs, car c'est bien ce que j'aime par dessus tout dans mon métier : les rencontres et le contact humain.",
    quote:
      "The only thing I do know... is that we have to be kind. Please, be kind - especially when we don't know what's going on. - Everything, Everywhere, All at Once - The Daniels, 2022",
    levelHtml: 100,
    levelCss: 100,
    levelJs: 100,
    isPerfect: true,
  },{
    id: 15,
    name: "Shrek",
    age: 32,
    img: "https://ih1.redbubble.net/image.2517271689.2840/raf,360x360,075,t,fafafa:ca443f4786.jpg",
    avatar: "./assets/avatar/marioBox.png",
    stack: "Js",
    gender: "./assets/icons/male.png",
    description:
      "Shrek",
    quote:
      "Shrek",
    levelHtml: 100,
    levelCss: 100,
    levelJs: 100,
    isPerfect: true,
  },
];

export default person